variable "region" {}
variable "zone" {}
variable "regional" {}
variable "cluster_name" {}
variable "initial_node_count" {}
variable "machine_type" {}
variable "vpc_id" {}
variable "subnetwork_id" {}
variable "gke_nodes" {}
variable "project_id" {}
variable "node_locations" {}
variable "oauth_scopes" {}
variable "disk_size_gb" {}